language: rust
sudo: false

install:
  - curl -L https://github.com/gohugoio/hugo/releases/download/v0.47.1/hugo_0.47.1_Linux-64bit.tar.gz |
    tar xzvf -
  - pip install --user awscli
  - ~/.local/bin/aws configure set preview.cloudfront true

script:
  - ci/test.sh
  - ./hugo

deploy:
  provider: script
  script: bash deploy_cn.sh
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = "false"
