---
baseurl: "https://tokio-cn.github.io"
title: "Tokio——Rust 编程语言的异步运行时。"
languageCode: "zh-cn"
canonifyURLs: "true"
googleAnalytics: "UA-122396021-1"

menu:
  docs:
    - identifier: "getting_started"
      name: "入门"
      weight: 1000
    - identifier: "topics"
      name: "Topics"
      weight: 2000
    - identifier: "reference"
      name: "API 文档"
      url: "https://docs.rs/tokio"
      weight: 9000
    - identifier: "network_utils"
      name: "Network Utilities"
      weight: 10000


# URL params used in /layouts/shortcodes
params:
  tokioDocsURL: "https://docs.rs/tokio/0.1/tokio"
  tokioExecutorDocsURL: "https://docs.rs/tokio-executor/0.1/tokio_executor"
  tokioIoDocsURL: "https://docs.rs/tokio-io/0.1/tokio_io"
  tokioCodecDocsURL: "https://docs.rs/tokio-codec/0.1/tokio_codec"
  tokioReactorDocsURL: "https://tokio-rs.github.io/tokio/tokio_reactor/"
  tokioTimerDocsURL: "https://docs.rs/tokio-timer/0.2"
  futuresDocsURL: "https://docs.rs/futures/0.1/futures"
  mioDocsURL: "https://docs.rs/mio/*/mio"
  coreDocsURL: "https://docs.rs/tokio-core/0.1/tokio_core"
  protoDocsURL: "https://tokio-rs.github.io/tokio-proto/tokio_proto"
  serviceDocsURL: "https://tokio-rs.github.io/tokio-service/tokio_service"
  bytesDocsURL: "https://docs.rs/bytes/0.4/bytes"
  tokio01URL: "https://v0-1--tokio.netlify.com/"
